name: Bandit Scan

permissions: {}

on:
  push:
    branches: [ version-0 ]
  pull_request:
    branches: [ version-0 ]

jobs:
  bandit-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      # with:
      #   # For pull requests, check out the base branch, not the PR branch
      #   ref: ${{ github.event.pull_request.base.sha }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        # TODO: workflow to test for python 3.9 or more
        python-version: '3.10'

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: |
        uv sync --extra test --extra dev

    - name: Run Bandit
      run: |
        uv add bandit
        uv run bandit -r . -f custom --msg-template "{abspath}:{line}: {severity}: {test_id}: {msg}" --exclude ./.venv
