name: Hibernate sample tests

permissions: {}

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/**'
      - 'dialect/**'
      - '.github/workflows/java-hibernate-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/**'
      - '.github/workflows/java-hibernate-tests.yml'
  # Give us a button to allow running the workflow on demand for testing.
  workflow_dispatch:

jobs:
  create-cluster:
    uses: ./.github/workflows/dsql-cluster-create.yml
    with:
      workflow_name: hibernate-tests
    secrets:
      AWS_IAM_ROLE: ${{ secrets.HIBERNATE_IAM_ROLE }}
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials

  test:
    needs: create-cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
   
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'corretto'
        architecture: x64
        cache: maven

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ secrets.HIBERNATE_IAM_ROLE }}
        aws-region: ${{ needs.create-cluster.outputs.region }}

    - name: Build dialect
      working-directory: ./dialect
      env:
        CLUSTER_ENDPOINT: ${{ needs.create-cluster.outputs.cluster-endpoint }}
        REGION: ${{ needs.create-cluster.outputs.region }}
        RUN_INTEGRATION: "TRUE"
      run: |
        ./gradlew build -i
        mvn install:install-file \
          -Dfile=build/libs/aurora-dsql-hibernate-dialect-1.0.0.jar \
          -DgroupId=software.amazon.dsql \
          -DartifactId=aurora-dsql-hibernate-dialect \
          -Dversion=1.0.0 \
          -Dpackaging=jar

    - name: Run sample application tests with dialect JAR
      working-directory: ./examples/pet-clinic-app
      run : |
        mvn validate
        mvn initialize
        mvn clean compile
        mvn test

    - name: Run DSQL integration test
      working-directory: ./examples/pet-clinic-app
      env:
        CLUSTER_ENDPOINT: ${{ needs.create-cluster.outputs.cluster-endpoint }}
        CLUSTER_USER: admin
        RUN_INTEGRATION: "TRUE"
      run: |
        mvn test -Dtest=DsqlIntegrationTest

  delete-cluster:
    if: always() && needs.create-cluster.result == 'success'
    needs: [create-cluster, test]
    uses: ./.github/workflows/dsql-cluster-delete.yml
    with:
      cluster-id: ${{ needs.create-cluster.outputs.cluster-id }}
      region: ${{ needs.create-cluster.outputs.region }}
    secrets:
      AWS_IAM_ROLE: ${{ secrets.HIBERNATE_IAM_ROLE }}
    permissions:
      id-token: write # required by aws-actions/configure-aws-credentials
