name: Deploy Hibernate to Maven Central

permissions: {}

on:
  push:
    tags:
      - "java/hibernate/v*"

defaults:
  run:
    working-directory: java/hibernate/dialect

jobs:
  wait-for-ci:
    name: Wait for CI to pass
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: ${{ github.sha }}
          running-workflow-name: "Wait for CI to pass"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

  deploy:
    needs: wait-for-ci
    runs-on: ubuntu-latest
    environment: maven
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Deploy to Central Portal
        run: |
          ./gradlew build
          ./gradlew publish
          ./gradlew jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_STAGE: "UPLOAD"
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

  update-changelog:
    name: Update changelog
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write # required by rhysd/changelog-from-release/action
      pull-requests: write # required by rhysd/changelog-from-release/action
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: java/hibernate/CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request: true
          args: -e ^java/hibernate/
