name: Deploy Hibernate to Maven Central

permissions: {}

on:
  push:
    tags:
      - "java/hibernate/v*"

defaults:
  run:
    working-directory: java/hibernate/dialect

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: maven
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Deploy to Central Portal
        run: |
          ./gradlew build
          ./gradlew publish
          ./gradlew jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_STAGE: "UPLOAD"
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
