name: Release Tortoise ORM

permissions: {}

on:
  push:
    tags:
      - "python/tortoise-orm/v*"

defaults:
  run:
    working-directory: python/tortoise-orm

jobs:
  wait-for-ci:
    name: Wait for CI to pass
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: ${{ github.sha }}
          running-workflow-name: "Wait for CI to pass"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

  build:
    name: Build distribution
    needs: wait-for-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@v7

      - name: Build distribution packages
        run: uv build

      - uses: actions/upload-artifact@v6
        with:
          name: python-tortoise-dist
          path: python/tortoise-orm/dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/aurora-dsql-tortoise-orm
    permissions:
      id-token: write # required by pypa/gh-action-pypi-publish

    steps:
      - uses: actions/download-artifact@v7
        with:
          name: python-tortoise-dist
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish to PyPI
    needs: publish-to-testpypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/aurora-dsql-tortoise-orm
    permissions:
      id-token: write # required by pypa/gh-action-pypi-publish

    steps:
      - uses: actions/download-artifact@v7
        with:
          name: python-tortoise-dist
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1

  update-changelog:
    name: Update changelog
    needs: publish-to-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write # required by rhysd/changelog-from-release/action
      pull-requests: write # required by rhysd/changelog-from-release/action
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: python/tortoise-orm/CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request: true
          version: ${{ github.ref_name }}
          args: -e ^python/tortoise-orm/
