name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write
  pull-requests: write

env:
  DEFAULT_BRANCH: version-0

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag for build & publish
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Add build/publish steps here that use the tagged version

      - name: Checkout default branch for changelog
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.DEFAULT_BRANCH }}

      - name: Update changelog
        uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request: true
