name: Release TypeScript Prisma

permissions: {}

on:
  push:
    tags:
      - "typescript/prisma/v*"

defaults:
  run:
    working-directory: typescript/prisma

jobs:
  wait-for-ci:
    name: Wait for CI to pass
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: ${{ github.sha }}
          running-workflow-name: "Wait for CI to pass"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

  build:
    name: Build distribution
    needs: wait-for-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - uses: actions/upload-artifact@v6
        with:
          name: typescript-prisma-dist
          path: |
            typescript/prisma/dist/
            typescript/prisma/package.json
            typescript/prisma/README.md
            typescript/prisma/CHANGELOG.md

  publish-to-npm:
    name: Publish to npm
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/@aws/aurora-dsql-prisma
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v7
        with:
          name: typescript-prisma-dist
          path: package/

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to npm
        working-directory: package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-changelog:
    name: Update changelog
    needs: publish-to-npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: typescript/prisma/CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request: true
          args: -e ^typescript/prisma/
